version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/scanner-pwa"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/operator-portal"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "weekly"
